source 'https://rubygems.org'

gem 'bcrypt-ruby'
gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'cloudinary'
gem 'carrierwave'
gem 'slim-rails'
gem 'lazybox'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'rails-i18n'
gem 'simple_form'
gem 'jquery-minicolors-rails'
gem 'airbrake'
gem 'bootstrap-material-design'
gem 'material_design_lite-rails'

group :development, :test do
  gem 'pry'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
