development:
  cloud_name: roka
  api_key: '481874395462385'
  api_secret: P4jPXTglC4tpu8xVaUVk4wAB0Q0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: roka
  api_key: '481874395462385'
  api_secret: P4jPXTglC4tpu8xVaUVk4wAB0Q0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: roka
  api_key: '481874395462385'
  api_secret: P4jPXTglC4tpu8xVaUVk4wAB0Q0
  enhance_image_tag: true
  static_image_support: false
